<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aeropuerto [
   <!ELEMENT aeropuerto (nombre, vuelos, fecha)>
   <!ELEMENT nombre (#PCDATA)>
   <!ELEMENT vuelos (vuelo+)>
   <!ELEMENT vuelo (diario?, origen, destino, hora-salida, hora-llegada)>
      <!ATTLIST vuelo código ID #REQUIRED>
      <!ATTLIST vuelo estado (C|E|R) "E">
   <!ELEMENT diario EMPTY>
   <!ELEMENT origen (#PCDATA)>
   <!ELEMENT destino (#PCDATA)>
   <!ELEMENT hora-salida (#PCDATA)>
   <!ELEMENT hora-llegada (#PCDATA)>
   <!ELEMENT fecha (#PCDATA)>
]>

<aeropuerto>
   <nombre>JFK</nombre>
   <vuelos>
      <vuelo código="V22" estado="R">
         <diario />
         <origen>New York</origen>
         <destino>Chicago</destino>
         <hora-salida>9:30</hora-salida>
         <hora-llegada>11:30</hora-llegada>
      </vuelo>
      <vuelo código="V23" estado="C">
         <origen>New York</origen>
         <destino>Miami</destino>
         <hora-salida>10:15</hora-salida>
         <hora-llegada>11:15</hora-llegada>
      </vuelo>
   </vuelos>
   <fecha>20/12/2013</fecha>
</aeropuerto>