=== jacuela/LENGUAJE_MARCAS/tema2_xml/03_XML SCHEMA/00_pruebas/06_agenda.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="agenda">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="contacto" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="email" type="xs:string"/>
              <xs:element name="sexo">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="mujer"/>
                        <xs:enumeration value="hombre"/>
                    </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="codigo_postal">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:length value="5"></xs:length>
                    </xs:restriction>
                </xs:simpleType>
              </xs:element>
             </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== jacuela/LENGUAJE_MARCAS/tema2_xml/03_XML SCHEMA/00_pruebas/06_agenda.xml
<?xml version="1.0" encoding="UTF-8"?>
<agenda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="06_agenda.xsd">
   <contacto>
    <nombre>Pepa Perez</nombre>
    <email>pepa@kk.com</email>
    <sexo>mujer</sexo>
    <codigo_postal>3007</codigo_postal>
   </contacto>
   <contacto>
    <nombre>Alfonso Arus</nombre>
    <email>alfonso.arus@kk.com</email>
    <sexo>nobinario</sexo>
    <codigo_postal>30160</codigo_postal>
   </contacto>
</agenda>
