=== jacuela/LENGUAJE_MARCAS/tema2_xml/03_XML SCHEMA/01_ejercicios/Ejercicio5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="aeropuerto">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="vuelos">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="vuelo" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="diario">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="SI"/>
                                                <xs:enumeration value="NO"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>
                                    <xs:element name="origen" type="xs:string"/>
                                    <xs:element name="destino" type="xs:string"/>
                                    <xs:element name="hora-salida" type="xs:time"/>
                                    <xs:element name="hora-llegada" type="xs:time"/>
                                </xs:sequence>
                                <xs:attribute name="codigo" type="xs:ID"/>
                                <xs:attribute name="estado">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="C"/>
                                            <xs:enumeration value="E"/>
                                            <xs:enumeration value="R"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="fecha" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== jacuela/LENGUAJE_MARCAS/tema2_xml/03_XML SCHEMA/01_ejercicios/Ejercicio5.xml
<?xml version="1.0" encoding="UTF-8"?>
<aeropuerto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Ejercicio5.xsd">
    <nombre>JFK</nombre>
    <vuelos>
       <vuelo codigo="V22" estado="X">
          <diario>SI</diario>
          <origen>New York</origen>
          <destino>Chicago</destino>
          <hora-salida>09:30:00</hora-salida>
          <hora-llegada>11:30:00</hora-llegada>
       </vuelo>
       <vuelo codigo="V23" estado="C">
          <diario>a veces</diario>
          <origen>New York</origen>
          <destino>Miami</destino>
          <hora-salida>10:15:00</hora-salida>
          <hora-llegada>11:15:00</hora-llegada>
       </vuelo>
    </vuelos>
    <fecha>2013-12-20</fecha>
 </aeropuerto>
