=== jacuela/LENGUAJE_MARCAS/tema2_xml/03_XML SCHEMA/01_ejercicios/Ejercicio2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="listaventas">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="venta" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:choice>
                        <xs:element name="ventaacredito">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="fechafinpago" minOccurs="0" type="xs:date"/>
                                    <xs:element name="cantidad" minOccurs="1">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:double">
                                                <xs:minInclusive value="0"/>
                                             </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="ventainmediata">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="cantidad" minOccurs="1">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:double">
                                                <xs:minInclusive value="0"/>
                                             </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>
                                    <xs:element name="divisa" minOccurs="1">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="euros"/>
                                                <xs:enumeration value="dolares"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== jacuela/LENGUAJE_MARCAS/tema2_xml/03_XML SCHEMA/01_ejercicios/Ejercicio2.xml
<?xml version="1.0" encoding="UTF-8"?>
<listaventas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Ejercicio2.xsd">
    <venta>
        <ventaacredito>
            <fechafinpago>2021-10-22</fechafinpago>
            <cantidad>21000</cantidad>
        </ventaacredito>
    </venta>
    <venta>
        <ventainmediata>
            <cantidad>1800</cantidad>
            <divisa>euros</divisa>
        </ventainmediata>
    </venta>
    <venta>
        <ventaacredito>
            <cantidad>21000</cantidad>
        </ventaacredito>
    </venta>
</listaventas>
