<?xml version="1.0" encoding="UTF-8"?>
<!-- Usando el anterior esquema, representa una biblioteca musical -->
<!DOCTYPE empleado [
    <!ELEMENT empleado (nombre,apellido1,apellido2,dni,direccion,telefonos,emails)>
        <!ATTLIST empleado codigo ID #REQUIRED>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellido1 (#PCDATA)>
    <!ELEMENT apellido2 (#PCDATA)>
    <!ELEMENT dni (#PCDATA)>
        <!ATTLIST dni tipo (NIF|NIE) #REQUIRED>
    <!ELEMENT direccion (calle,numero, piso, puerta,cp, poblacion, provincia)>
    <!ELEMENT calle (#PCDATA)>
    <!ELEMENT numero (#PCDATA)>
    <!ELEMENT piso (#PCDATA)>
    <!ELEMENT puerta  (#PCDATA)>
    <!ELEMENT cp  (#PCDATA)>
    <!ELEMENT poblacion  (#PCDATA)>
    <!ELEMENT provincia  (#PCDATA)>
    
    <!ELEMENT telefonos (telefono)+>
    <!ELEMENT telefono (#PCDATA)>
        <!ATTLIST telefono principal (SI|NO) #IMPLIED>
    <!ELEMENT emails (email)+>
    <!ELEMENT email (#PCDATA)>
        <!ATTLIST email principal (SI|NO) #IMPLIED>
    
]>
<empleado codigo="E1001">
    <nombre>John</nombre>
    <apellido1>Colling</apellido1>
    <apellido2></apellido2>
    <dni tipo="NIE">X0124567A</dni>
    <direccion>
        <calle>Lucianos</calle>
        <numero>11</numero>
        <piso></piso>
        <puerta></puerta>
        <cp>30007</cp>
        <poblacion>Murcia</poblacion>
        <provincia>Murcia</provincia>
    </direccion>
    <telefonos>
        <telefono principal="SI">600121212</telefono>
        <telefono>968121212</telefono>
    </telefonos>
    <emails>
        <email principal="SI">john@gmail.com</email>
    </emails>
</empleado>
